---
- name: Create Nginx user
  ansible.builtin.user:
    name: nginx
    system: true
    home: /nonexistent
    shell: /usr/sbin/nologin

- name: Install Nginx and other dependencies
  ansible.builtin.include_tasks: install.yml

- name: Deploy app to server
  ansible.builtin.include_tasks: app.yml

- name: Add vhost file and enable app
  ansible.builtin.include_tasks: vhost.yml

- name: Validate Nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false

- name: Ensure nginx service is running as configured.
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
