---
- name: Create Nginx user
  ansible.builtin.user:
    name: '{{ nginx_user }}'
    system: true
    home: /nonexistent
    shell: /usr/sbin/nologin

- name: Install Nginx and other dependencies
  ansible.builtin.include_tasks: install.yml

- name: Deploy app to server
  ansible.builtin.include_tasks: app.yml

- name: Add vhost file and enable app
  ansible.builtin.include_tasks: vhost.yml

- name: Generate certificate and setup automatic renewal
  ansible.builtin.include_tasks: certbot.yml

- name: Backup default configuration file
  ansible.builtin.command:
    cmd: cp -p /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
    creates: /etc/nginx/nginx.conf.bak

- name: Add managed configuration file
  ansible.builtin.template:
    src: templates/nginx.conf.v2
    dest: /etc/nginx/nginx.conf
    force: true
    owner: nginx
    group: nginx
    mode: '0644'

- name: Validate Nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false

- name: Ensure nginx service is running as configured
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
