---
galaxy_info:
  role_name: tailscale
  author: Aapo Kokko
  description: Install Tailscale and join the host to the tailnet.
  license: MIT
  min_ansible_version: '2.15'
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies: []
