---
- name: Add admin user {{ server_init_admin }}
  ansible.builtin.user:
    name: '{{ server_init_admin }}'
    groups: sudo,adm
    append: true
    shell: /bin/bash
    password: "{{ server_init_admin_pass | password_hash('sha512') }}"
  become: true
  when: ansible_user_id != lookup('ansible.builtin.vars', 'server_init_admin')

- name: Add SSH key for admin user {{ server_init_admin }}
  ansible.posix.authorized_key:
    user: '{{ server_init_admin }}'
    key: '{{ server_init_admin_pubkey }}'
  become: true
  when: ansible_user_id != lookup('ansible.builtin.vars', 'server_init_admin')

- name: Disable root password
  ansible.builtin.user:
    name: root
    password: !
  become: true
  when: ansible_user_id != 'root'

- name: Disable password login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: PasswordAuthentication no
  become: true
  notify: Restart SSH
  when: ansible_user_id != 'root'

- name: Disable root login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: PermitRootLogin no
  become: true
  notify: Restart SSH
  when: ansible_user_id != 'root'
