---
- name: Add admin user and secure login
  ansible.builtin.include_tasks: login.yml

- name: Install required packages
  ansible.builtin.include_tasks: apt.yml

- name: Add swap space
  ansible.builtin.include_tasks: swap.yml

- name: Miscellaneous tasks
  ansible.builtin.include_tasks: misc.yml
